# -*- coding: utf-8 -*-
"""Untitled61.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzhiO52Qjg4QW62W_Xduu0mAibQ0LVJc
"""

import numpy as np

# AND Gate Dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([0,0,0,1])

def train_perceptron(X, y, lr=0.1, epochs=10):
    weights = np.zeros(X.shape[1])
    bias = 0

    for epoch in range(epochs):
        for i in range(len(X)):
            linear_output = np.dot(X[i], weights) + bias

            y_pred = 1 if linear_output >= 0 else 0

            update = lr * (y[i] - y_pred)

            weights += update * X[i]
            bias += update

    return weights, bias

weights, bias = train_perceptron(X, y)

print("Final Weights:", weights)
print("Final Bias:", bias)

print("\nPredictions")
for sample in X:
    output = np.dot(sample, weights) + bias
    prediction = 1 if output >= 0 else 0
    print(sample, "->", prediction)

import numpy as np
import matplotlib.pyplot as plt

# AND Gate Dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([0,0,0,1])

# Trained weights and bias
weights = np.array([0.2, 0.1])
bias = -0.2

# Plot data points
for i in range(len(X)):
    if y[i] == 0:
        plt.scatter(X[i,0], X[i,1], color='blue', marker='o', s=100, label='Class 0' if i==0 else "")
    else:
        plt.scatter(X[i,0], X[i,1], color='red', marker='^', s=120, label='Class 1')

# Decision boundary: w1*x1 + w2*x2 + b = 0
x1 = np.linspace(-0.2, 1.2, 100)

# Avoid division by zero
if weights[1] != 0:
    x2 = -(weights[0]*x1 + bias) / weights[1]
    plt.plot(x1, x2, 'k-', linewidth=2, label='Decision Boundary')

# Labels
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Perceptron Decision Boundary (AND Gate)")
plt.grid(True)
plt.legend()

plt.show()

import tensorflow as tf
import numpy as np

# XOR Dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype=float)

y = np.array([0,1,1,0])

experiments = [
    ("sigmoid",0.01),
    ("sigmoid",0.1),
    ("relu",0.01),
    ("relu",0.1)
]

results=[]

for activation, lr in experiments:

    model=tf.keras.Sequential([
        tf.keras.layers.Dense(4,input_shape=(2,),activation=activation),
        tf.keras.layers.Dense(1,activation='sigmoid')
    ])

    optimizer=tf.keras.optimizers.Adam(learning_rate=lr)

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    history=model.fit(
        X,y,
        epochs=100,
        verbose=0
    )

    loss=history.history['loss'][-1]
    acc=history.history['accuracy'][-1]

    results.append([activation,lr,loss,acc])

print("\nResults")
for r in results:
    print(r)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

pred = model.predict(X)
pred = (pred > 0.5).astype(int)

accuracy = accuracy_score(y, pred)
precision = precision_score(y, pred)
recall = recall_score(y, pred)
f1 = f1_score(y, pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris=load_iris()

X=iris.data
y=iris.target

scaler=StandardScaler()
X=scaler.fit_transform(X)

X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

learning_rates=[0.001,0.01]
hidden_units=[8,16]
dropouts=[0.0,0.2]

trial=1

for lr in learning_rates:
    for hidden in hidden_units:
        for dropout in dropouts:

            model=tf.keras.Sequential([
                tf.keras.layers.Dense(hidden,activation='relu'),
                tf.keras.layers.Dropout(dropout),
                tf.keras.layers.Dense(3,activation='softmax')
            ])

            model.compile(
                optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy']
            )

            history=model.fit(
                X_train,
                y_train,
                epochs=50,
                verbose=0,
                validation_data=(X_test,y_test)
            )

            train_loss=history.history['loss'][-1]
            val_acc=history.history['val_accuracy'][-1]

            print("\nTrial",trial)
            print("Learning Rate:",lr)
            print("Hidden Units:",hidden)
            print("Dropout:",dropout)
            print("Training Loss:",train_loss)
            print("Validation Accuracy:",val_acc)

            trial+=1

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

pred = model.predict(X_test)
pred = np.argmax(pred, axis=1)

accuracy = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred, average='weighted')
recall = recall_score(y_test, pred, average='weighted')
f1 = f1_score(y_test, pred, average='weighted')

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

import tensorflow as tf
from tensorflow.keras import layers,models
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

# Load Data
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

# Normalize
x_train=x_train/255.0
x_test=x_test/255.0

# Build Model
model=models.Sequential([
    layers.Flatten(input_shape=(28,28)),
    layers.Dense(128,activation='relu'),
    layers.Dense(64,activation='relu'),
    layers.Dense(10,activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history=model.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)

# Evaluate
loss,accuracy=model.evaluate(x_test,y_test)

print("Test Accuracy:",accuracy)

# Predictions
pred=model.predict(x_test)
pred=np.argmax(pred,axis=1)

cm=confusion_matrix(y_test,pred)

plt.figure(figsize=(8,8))
plt.imshow(cm,cmap='Blues')
plt.colorbar()
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

pred = model.predict(x_test, verbose=0)
pred = np.argmax(pred, axis=1)

accuracy = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred, average='weighted')
recall = recall_score(y_test, pred, average='weighted')
f1 = f1_score(y_test, pred, average='weighted')

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

import matplotlib.pyplot as plt
import numpy as np

# Predict on test data
predictions = model.predict(x_test, verbose=0)
predicted_labels = np.argmax(predictions, axis=1)

# Find misclassified images
misclassified = np.where(predicted_labels != y_test)[0]

print("Total Misclassified Images:", len(misclassified))

# Display first 3 misclassified images
for i in range(3):
    idx = misclassified[i]

    plt.figure(figsize=(2,2))
    plt.imshow(x_test[idx], cmap='gray')
    plt.title(f"Image ID: {idx}\nTrue: {y_test[idx]}  Predicted: {predicted_labels[idx]}")
    plt.axis('off')
    plt.show()

    print("Image ID:", idx)
    print("True Label:", y_test[idx])
    print("Predicted Label:", predicted_labels[idx])
    print("-"*40)